In [1]:
from thirdparty.other_models import *

In [2]:
from tune import *

In [3]:
dataset_name = "rotten_tomatoes"
model_name = "XLNet"

In [4]:
train_dataset = load_dataset(dataset_name, split='train')
test_dataset = load_dataset(dataset_name, split='test')

Using custom data configuration default
Reusing dataset rotten_tomatoes_movie_review (C:\Users\Yizhou Zhao\.cache\huggingface\datasets\rotten_tomatoes_movie_review\default\1.0.0\9198dbc50858df8bdb0d5f18ccaf33125800af96ad8434bc8b829918c987ee8a)
Using custom data configuration default
Reusing dataset rotten_tomatoes_movie_review (C:\Users\Yizhou Zhao\.cache\huggingface\datasets\rotten_tomatoes_movie_review\default\1.0.0\9198dbc50858df8bdb0d5f18ccaf33125800af96ad8434bc8b829918c987ee8a)


In [5]:
train_data_sampler = RandomDataSampler(max_train_samples, len(train_dataset))
#test_data_sampler = TuncatedDataSampler([1 for _ in range(1024)]) if max_test_samples is not None else None

In [6]:
#train_data_loader = torch.utils.data.DataLoader(train_dataset, sampler=train_data_sampler, batch_size=batch_size)
#test_data_loader = torch.utils.data.DataLoader(test_dataset, sampler=test_data_sampler, batch_size=batch_size)

train_data_loader = torch.utils.data.DataLoader(train_dataset, sampler = train_data_sampler,  batch_size=batch_size)


In [7]:
num_labels = len(set([item["label"] for item in train_dataset]))

In [8]:
num_labels

2

In [9]:
model = AnotherNet(model_name, num_labels)

In [10]:
for batch_data in train_data_loader:
    batch_x = model.tokenizer(batch_data['text'], padding=True, truncation=True, max_length=max_input_length, return_tensors="pt").input_ids
    batch_label = batch_data['label']
    
    
    break

In [11]:
batch_x.shape

torch.Size([8, 55])

In [12]:
batch_label.shape

torch.Size([8])

In [13]:
batch_label

tensor([1, 0, 0, 1, 0, 1, 0, 1])

In [15]:
if use_cuda:
    batch_x = batch_x.to(torch.device("cuda"))
    batch_label = batch_label.to(torch.device("cuda"))

In [16]:
loss_fct =  torch.nn.CrossEntropyLoss()
optimizer = Adafactor(model.parameters())

if use_cuda:
    model = model.cuda()

In [17]:
output_logits = model(batch_x)
loss = loss_fct(output_logits, batch_label)

In [18]:
loss

tensor(0.6833, device='cuda:0', grad_fn=<NllLossBackward>)

In [ ]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [19]:
(torch.sum(torch.argmax(output_logits,dim=1) == batch_label) / len(batch_label)).item()

0.25

In [20]:
output_logits

tensor([[-0.2127, -0.3297],
        [ 0.1861,  0.3745],
        [-0.1538, -1.0801],
        [-0.0596, -0.4556],
        [-0.1859, -0.8184],
        [-0.2352, -0.3711],
        [-0.3059, -0.1750],
        [-0.1273, -0.1933]], device='cuda:0', grad_fn=<AddmmBackward>)

In [21]:
batch_label

tensor([1, 0, 0, 1, 0, 1, 0, 1], device='cuda:0')

In [31]:
a = torch.randn(5,2)
b = torch.empty(5).random_(2)

In [32]:
print(a, b)

tensor([[ 0.2285,  0.7983],
        [ 0.0080, -0.2523],
        [-1.0895, -0.7939],
        [ 0.4908,  1.1494],
        [-2.2138,  1.4180]]) tensor([0., 0., 1., 1., 1.])


In [33]:
calculate_accuracy(torch.randn(5,2), torch.empty(5).random_(2))

0.800000011920929

In [34]:
torch.argmax(a,dim=1)

tensor([1, 0, 1, 1, 1])